# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/akshaykarle/go-http-digest-auth-client"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/akshaykarle/go-mongodbatlas"

[[constraint]]
  name = "github.com/akshaykarle/terraform-provider-mongodbatlas"
  version = "0.7.3"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.8"
